### PR TITLE
Update CHANGEME.md

### PR DESCRIPTION
**Pull request by mayankjaiswal1709**

### CODE REVIEW

**Comment by ParanoidUser** [comment]
Good job, @mayankjaiswal1709! Repeat the same steps again to open `Pull Shark` badge. 🤓

**Comment by mayankjaiswal1709** [comment]
ohky

**Comment by mayankjaiswal1709** [comment]
done

**Comment by ParanoidUser** [comment]
Well done! If you run the same steps again (but assign a reviewer before merging PR) you should get your [YOLO](https://github.com/ParanoidUser/yolo/discussions/18) 😊

**Comment by mayankjaiswal1709** [comment]
ohky

**Comment by ParanoidUser** [comment]
> ohky

Hmm... PR #499 didn't have any reviewers assigned 🤔

**Comment by mayankjaiswal1709** [comment]
but  i changed

**Comment by mayankjaiswal1709** [comment]
is it ohky now

**Pull request merged**
