### PR TITLE
Heidet patch 1 1

### PR DESCRIPTION
**Pull request by Heidet**
Update changelog

### CODE REVIEW

**Review by NomanGhiasy — COMMENTED** [review]
@ParanoidUser

**Comment by ParanoidUser** [comment]
@Heidet / @NomanGhiasy, so what has changed in this PR?

**Review by NomanGhiasy — COMMENTED** [review]
I could not figure out what changed, couple of file's got deleted there's not a way to properly review this.

**Comment by ParanoidUser** [comment]
So do I. @Heidet, please be aware of the [contribution](https://github.com/ParanoidUser/yolo/blob/main/docs/CONTRIBUTING.md) guidelines in place. Closing as this PR needs to be reworked.

**Pull request closed without merging**
