### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by marcos-jesus**
done. 👍🏼 🥇

### CODE REVIEW

**Comment by ParanoidUser** [comment]
@marcos-jesus, I'm sorry but I might confuse you. Do you see the `Merge pull request` button on your end?

**Comment by ParanoidUser** [comment]
> yes, i see Button green writing Merge pull request, I need make merge now ? what is next step ?

Yes, please. Just merge it and that should be it.

**Comment by ParanoidUser** [comment]
Ta-dam! 😄 Congrats on your new badge! 
image

**Comment by marcos-jesus** [comment]
oooh thanks very much guys.

**Comment by ParanoidUser** [comment]
No problem! If that doesn't bother you, could you mark "as answer" any of my responses in Discussions?

**Comment by marcos-jesus** [comment]
sure my friend. 😄

**Comment by marcos-jesus** [comment]
> @marcos-jesus, I'm sorry but I might confuse you. Do you see the `Merge pull request` button on your end?
> 
> We need that one, **NOT** `Close pull request`. I'll update the instructions right away to avoid any confusion in the future.


all right ? or no ?

**Comment by marcos-jesus** [comment]
> No problem! If that doesn't bother you, could you mark "as answer" any of my responses in Discussions?


I think it's like this

**Pull request merged**
