### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by lucas-0liveira**

### CODE REVIEW

**Comment by lucas-0liveira** [comment]
I'm having problems like 'Merging is blocked' and 'Code owner review required' @ParanoidUser

**Comment by ParanoidUser** [comment]
@lucas-0liveira, the intention of this PR is unclear to me. Please explain what you're trying to accomplish and I'll be happy to help. Just for reference, I'd recommend reading through the [contributing guides](https://github.com/ParanoidUser/yolo/blob/main/docs/CONTRIBUTING.md).

**Comment by lucas-0liveira** [comment]
I can't click 'Squash and merge' to get the YOLO badge

**Comment by lucas-0liveira** [comment]
I can't click 'Squash and merge' to get the YOLO badge, Merging is blocked for me

**Comment by lucas-0liveira** [comment]
a

**Comment by ParanoidUser** [comment]
1. We're trying to keep the `main` branch static, so it's now locked for changes;
2. The active `changeme` branch is open for experimentation and badge earning;
3. If you are interested in earning YOLO badge, here are some steps to try https://github.com/ParanoidUser/yolo/discussions/18;

**Pull request closed without merging**
