### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FleetAdmiralJakob**

### CODE REVIEW

**Comment by FleetAdmiralJakob** [comment]
@ParanoidUser Can you give me the rights so I can merge the PR?

**Comment by ParanoidUser** [comment]
Hey @FleetAdmiralJakob! I was under impression that all collaborators should have "write" permission by default.
Do you see this option from your side?

image

**Comment by FleetAdmiralJakob** [comment]
> Hey @FleetAdmiralJakob! I was under impression that all collaborators should have "write" permission by default. Do you see this option from your side?
> 
> image

Nope
image

**Comment by ParanoidUser** [comment]
I removed the need for approval, could you check if it helps?

**Comment by ParanoidUser** [comment]
@FleetAdmiralJakob, if it still doesn't work, feel free to send me a collaboration request to join your fork. As an owner there, you should have full control over PRs.

**Comment by ParanoidUser** [comment]
@FleetAdmiralJakob, congrats on the new YOLO badge! 🧐

**Comment by marcos-jesus** [comment]
To github.com:ParanoidUser/yolo.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:ParanoidUser/yolo.git'

Remove please.

**Pull request merged**
